#!/usr/bin/env bash
#  A Script that configures a new Ubuntu machine to Perform a 301-redirection

# Upadate Packages and Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Perform 301 Redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart nginx service
sudo service nginx restart
