#!/usr/bin/env bash

# SSH client configuration to use the private key

Host *
  PasswordAuthentication no
  IdentityFile ~/.ssh/school
  SendEnv LANG LC_*
  HashKnownHosts yes
  GSSPAIAuthentication yes
  GSSPAIDelegateCredentials no
